---

- name: OPERATING SYSTEM | Set timezone America/Sao_Paulo
  community.general.timezone:
    name: America/Sao_Paulo

- name: OPERATING SYSTEM | Update system
  yum:
    name: "*"
    state: latest

- name: OPERATING SYSTEM | Install common packages
  yum:
    name: "{{ packages }}"
    state: latest

- name: OPERATING SYSTEM | Stop and disable Firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: OPERATING SYSTEM | Disable Selinux
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: OPERATING SYSTEM | Disable Selinux into /etc/selinux/config
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=permissive

- name: AWX | Install/Configure K3s
  shell: "{{ item }}"
  with_items:
    - curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644

- name: AWX | Create folder /usr/local/src/awx-operator
  ansible.builtin.file:
    path: /usr/local/src/awx-operator
    state: directory
    mode: '0755'

- name: AWX | Clone repo AWX-OPERATOR
  ansible.builtin.git:
    repo: 'https://github.com/ansible/awx-operator.git'
    dest: /usr/local/src/awx-operator
    version: 0.20.0

- name: AWX | Setting environment variable
  shell: "{{ item }}"
  with_items:
    - cd /usr/local/src/awx-operator && make deploy
  environment:
    NAMESPACE: awx

...
