---

- name: OPERATING SYSTEM | Set timezone America/Sao_Paulo
  community.general.timezone:
    name: America/Sao_Paulo

- name: OPERATING SYSTEM | Update system
  yum:
    name: "*"
    state: latest

- name: OPERATING SYSTEM | Install common packages
  yum:
    name: "{{ packages }}"
    state: latest

- name: OPERATING SYSTEM | Stop and disable Firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: OPERATING SYSTEM | Disable Selinux
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: OPERATING SYSTEM | Disable Selinux into /etc/selinux/config
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=permissive

...
