---

- name: OPERATING SYSTEM | Set timezone America/Sao_Paulo
  shell: "{{ item }}"
  with_items:
    - timedatectl set-timezone America/Sao_Paulo

- name: OPERATING SYSTEM | Update system
  yum:
    name: "*"
    state: latest

- name: OPERATING SYSTEM | Install common packages
  yum:
    name: "{{ packages }}"
    state: latest

- name: OPERATING SYSTEM | Stop and disable Firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: OPERATING SYSTEM | Disable Selinux
  ansible.posix.selinux:
    policy: targeted
    state: permissive

...
