---

- name: OPERATING SYSTEM | Set timezone America/Sao_Paulo
  shell: "{{ item }}"
  with_items:
    - timedatectl set-timezone America/Sao_Paulo

- name: OPERATING SYSTEM | Update system
  yum:
    name: "*"
    state: latest

- name: OPERATING SYSTEM | Install common packages
  yum:
    name: "{{ packages }}"
    state: latest

- name: OPERATING SYSTEM | Stop and disable Firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: OPERATING SYSTEM | Check status SELINUX
  shell: "{{ item }}"
  ignore_errors: yes
  with_items: 
    - sestatus | grep enforced
  register: sestatus

- name: Disable SELINUX
  shell: "{{ item }}"
  with_items:
    - sudo sed -i s/^SELINUX=.*$/SELINUX=permissive/ /etc/selinux/config && sudo setenforce 0
  when: sestatus.results[0].stdout != "0"

...
