---

    - name: Set timezone America/Sao_Paulo
      shell: "{{ item }}"
      with_items:
        - timedatectl set-timezone America/Sao_Paulo

    - name: Update system
      yum:
        name: "*"
        state: latest

    - name: OPERATING SYSTEM | Install common packages
      yum:
        name: "{{ packages }}"
        state: latest

    - name: OPERATING SYSTEM | Restart and enable services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
        - firewalld

    - name: Disable SELINUX
      shell: "{{ item }}"
      with_items:
        - sudo sed -i s/^SELINUX=.*$/SELINUX=permissive/ /etc/selinux/config && sudo setenforce 0
